[package]
name = "balance-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = { version = "0.28", features = ["keys-bip39", "use-esplora-blocking"] }
clap = { version = "4.5", features = ["derive"] }
