[package]
name = "balance-checker"
version.workspace = true
edition.workspace = true

[dependencies]
bdk = { workspace = true, features = ["keys-bip39", "use-esplora-blocking"] }
clap.workspace = true
