[package]
name = "address-generator"
version.workspace = true
edition.workspace = true

[dependencies]
bdk_wallet = { workspace = true, features = ["keys-bip39"] }
clap.workspace = true
rand.workspace = true