[package]
name = "address-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_wallet = { version = "1.0", features = ["keys-bip39"] }
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"