[package]
name = "block-explorer"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true
